nav:
  - 主页: 'index.md'
  - 样式指南: 'styleguide.md'
  - 入门:
    - 概述: 'gettingstarted/index.md'
    - Mod的结构: 'gettingstarted/structuring.md'
    - Forge更新检查器: 'gettingstarted/autoupdate.md'
    - 依赖管理: 'gettingstarted/dependencymanagement.md'
    - 调试分析器: 'gettingstarted/debugprofiler.md'
  - 概念:
    - Sides: 'concepts/sides.md'
    - 资源: 'concepts/resources.md'
    - 注册表: 'concepts/registries.md'
    - Jar签名: 'concepts/jarsigning.md'
    - 国际化和本地化: 'concepts/internationalization.md'
  - 方块:
    - 概述: 'blocks/blocks.md'
    - 方块互动: 'blocks/interaction.md'
  - 方块状态:
    - 方块状态介绍: 'blockstates/states.md'
    - 方块状态JSON介绍: 'blockstates/introduction.md'
    - Forge方块状态JSON: 'blockstates/forgeBlockstates.md'
  - TileEntity:
    - 特殊渲染器: 'tileentities/tesr.md'
  - 物品:
    - 主页: 'items/items.md'
    - 战利品表: 'items/loot_tables.md'
  - 事件:
    - 基本用法: 'events/intro.md'
  - 网络:
    - 主页: 'networking/index.md'
    - 概述: 'networking/overview.md'
    - SimpleImpl: 'networking/simpleimpl.md'
  - 数据储存:
    - 能力系统: 'datastorage/capabilities.md'
    - World Saved Data: 'datastorage/worldsaveddata.md'
    - 拓展实体属性: 'datastorage/extendedentityproperties.md'
  - 工具:
    - 矿物词典: 'utilities/oredictionary.md'
  - 效果:
    - 音效: 'effects/sounds.md'
  - 惯例:
    - 版本命名: 'conventions/versioning.md'
    - 文件位置: 'conventions/locations.md'
    - 加载阶段: 'conventions/loadstages.md'
  - 参与Forge开发:
    - 入门: 'forgedev/index.md'
    - PR指南: 'forgedev/prguidelines.md'

# Do not edit in PRs below here
site_name: Forge文档

markdown_extensions:
  - admonition
  - smarty
  - sane_lists
  - pymdownx.superfences
  - pymdownx.highlight:
      use_pygments: false
  - toc:
      permalink: ' '

theme:
  name: null
  custom_dir: forge_theme
# Technically deprecated, but RTD overrides theme.custom_dir with their default style
# They still seem to respect the old option, though
# theme_dir: forge_theme
