pages:
  - 主页: 'index.md'
  - 样式指南: 'styleguide.md'
  - 入门:
    - 概述: 'gettingstarted/index.md'
    - Mod的结构: 'gettingstarted/structuring.md'
    - Forge更新检查器: 'gettingstarted/autoupdate.md'
  - 概念:
    - Sides: 'concepts/sides.md'
    - 注册表: 'concepts/registries.md'
  - 方块:
    - 概述: 'blocks/blocks.md'
    - 方块互动: 'blocks/interaction.md'
  - 方块状态:
    - 方块状态介绍: 'blockstates/states.md'
    - 方块状态JSON介绍: 'blockstates/introduction.md'
    - Forge方块状态JSON: 'blockstates/forgeBlockstates.md'
  - 物品:
    - 主页: 'items/items.md'
  - 事件:
    - 基本用法: 'events/intro.md'
  - 网络:
    - 主页: 'networking/index.md'
    - 概述: 'networking/overview.md'
    - SimpleImpl: 'networking/simpleimpl.md'
  - 数据储存:
    - 能力系统: 'datastorage/capabilities.md'
    - World Saved Data: 'datastorage/worldsaveddata.md'
    - 拓展实体属性: 'datastorage/extendedentityproperties.md'
  - 工具:
    - 矿物词典: 'utilities/oredictionary.md'
  - 效果:
    - 音效: 'effects/sounds.md'
  - 惯例:
    - 版本命名: 'conventions/versioning.md'
    - 文件位置: 'conventions/locations.md'
    - 加载阶段: 'conventions/loadstages.md'


# Do not edit in PRs below here
site_name: Forge文档

markdown_extensions:
  - admonition
  - smarty
  - sane_lists

extra_css:
  - css/style_fixes.css

theme: readthedocs
